### ISSUE TITLE
Can't select year in input year

### ISSUE THREAD

**Issue by njacob1001** [strapi/buffet#130]
Why the datepicker component doesn allow a year selection?

**Comment by soonzhi** [comment]
any fix for this?

**Comment by saadmb** [comment]
Any update on this issue? The DatePicker is useless without this option.

**Comment by mrocha98** [comment]
Would be great to select the month too

**Comment by alexmachina** [comment]
Any update? This is important

**Comment by crussell42** [comment]
Cant believe how broken the DatePicker is. This renders strapi admin basically useless.
This issue is very old. Has anybody even tested the date picker on buffetjs.io?
Try entering a date from 1966.

**Comment by MattieBelt** [comment]
The new design system for Strapi `v4` will include an updated DatePicker, checkout: https://design-system-mbcreimd0-strapijs.vercel.app/?path=/story/design-system-molecules-datepicker--base

**Comment by njacob1001** [comment]
great!
