### ISSUE TITLE
Custom List cannot accept jsx element as icon

### ISSUE THREAD

**Issue by AnonK2** [strapi/buffet#141]
I tried using the same component as https://buffetjs.io/storybook/?path=/story/custom--list but i got an error "Uncaught TypeError: Converting circular structure to JSON", i believe the cause of this bug is inside List component from @buffetjs/custom => <React.Fragment key={JSON.stringify(item)}>. the bug is from trying to stringify the jsx element of the icon. After i changed the key it fixed the issue. i hope the team will fix it soon. :D

**Comment by soupette** [comment]
This issue seems to be fixed. Feel free to reopen it with a more detailed step in order to reproduce the bug.
