### ISSUE TITLE
Datetime is sending onChange event on initial render

### ISSUE THREAD

**Issue by soupette** [strapi/buffet#145]
The Datetime component is sending an unwanted onChange event during it's first render. Thus changing the initial value to a moment object.

https://github.com/strapi/strapi/issues/7045

**Comment by ericliu-el** [comment]
Hi @soupette ,

This is my first PR #149 

It's a great project, and I want to help with it if it's possible.

Please let me know if there are any issues about my PR. 

Many thanks.

**Comment by soupette** [comment]
Thanks a lot I am checking it!
