### ISSUE TITLE
Website is not secure

### ISSUE THREAD

**Issue by bidoubiwa** [strapi/buffet#190]
You might have forgotton to update your SSL certificate! Just in case you did not notice :) 

https://www.buffetjs.io/

**Comment by soupette** [comment]
Thank you @bidoubiwa we have just fixed it!
I am closing the issue

**Comment by bidoubiwa** [comment]
The SSL certificate should be updated again :)

**Comment by bidoubiwa** [comment]
! The SSL certificate should be updated again :)

**Comment by soupette** [comment]
We are planning on removing the website since we have released a new Design system so I guess it won't be an issue.
