### ISSUE TITLE
Not passing className prop to the underlying DOM element

### ISSUE THREAD

**Issue by BoyWithSilverWings** [strapi/buffet#32]
From styled-components docs:

> The styled method works perfectly on all of your own or any third-party component, as long as they attach the passed className prop to a DOM element

With Buffet being a styled components based library itself, I expected this to be followed so we can override styles on provided components. But looks like it isn't on most components. 

Is this a conscious decision? If yes, how do you suggest that we override specific styles on components?

**Comment by soupette** [comment]
@BoyWithSilverWings it's a mistake from our part, maybe you can make a small PR so it is fixed?

**Comment by BoyWithSilverWings** [comment]
@soupette Sure, I would like to pick this one up 😄
