### ISSUE TITLE
Feature request: WYSIWYG Editor component

### ISSUE THREAD

**Issue by micheleriva** [strapi/buffet#35]
Hi!
Buffet is actually an amazing component library, great job! Are you planning to make the WYSIWYG editor component on Storybook?

**Comment by xargr** [comment]
I think this can added later as 3rd part library. If the core team include editor in library this will increase the cost of library.

**Comment by micheleriva** [comment]
I do agree that it will increase the cost of the library... but I've been struggling for a while looking for a WYSIWYG edito who can:

1) Upload images
2) Write markdown
3) Write code blocks

and Strapi editor is the first one I've found with these features. So I'm looking forward to use it even outside Strapi!

**Comment by soupette** [comment]
@micheleriva you can easily add the wyswiyg component from strapi to your application by taking the code from the [entry point file](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/admin/src/components/WysiwygWithErrors)

**Comment by micheleriva** [comment]
Thank you so much @soupette !
