### ISSUE TITLE
Allow custom icons in button component

### ISSUE THREAD

**Issue by BoyWithSilverWings** [strapi/buffet#37]
[Button Component](https://www.buffetjs.io/storybook/?path=/story/components--button) is currently accepting an `icon` prop and on `true` it is adding a `+` icon. 

Instead of having a prop to add a specific icon, can't we support custom icons?

**Expected Behavior:**
1. Since we are importing all of [font awesome](https://fontawesome.com/cheatsheet) fonts, show the `fa` icon with name string user is passing in.
2. If user is passing in a custom component, (svg or image), render that instead.

**Comment by soupette** [comment]
Agreed, we will make the update soon!

Although, if you feel like developing it would be awesome!

**Comment by BoyWithSilverWings** [comment]
@soupette  Looking at the code, I was wondering if it would be better ot use a library like [react-fontawesome](https://github.com/FortAwesome/react-fontawesome) so that we can bundle only the icons we need and not require the user to download the fonts anyway.

**Comment by soupette** [comment]
It might be a good idea but I am thinking that we can extend the customisation so the user can be able to pass an image or an svg as a prop.

**Comment by BoyWithSilverWings** [comment]
sure, that's a good idea. 
My proposal was that, we refractor to use react-font-awesome and fontawesome-svg-core so that we don't ship the entire font awesome library to the end user. This is for the internal icons such as the one used in checkbox. This would reduce the package size. 
The API for button would be:
1. An optional icon prop of type Node that would be rendered as user passes it.

**Comment by soupette** [comment]
I totally agree!
Is it something that you would like to work on, or should I include it in our roadmap?

**Comment by BoyWithSilverWings** [comment]
I would love to work on it

**Comment by soupette** [comment]
Awesome! Thanks @BoyWithSilverWings
