### ISSUE TITLE
Unnecessary use of css function

### ISSUE THREAD

**Issue by BoyWithSilverWings** [strapi/buffet#48]
From the docs for [css](https://www.styled-components.com/docs/api#css) API from styled components:

> A helper function to generate CSS from a template literal with interpolations. You need to use this if you return a template literal with functions inside an interpolation due to how tagged template literals work in JavaScript.
> If you're interpolating a string you do not need to use this, only if you're interpolating a function.

The repository is using these functions in many places where it is unnecessary.
[An example from Button](https://github.com/strapi/buffet/blob/ae9107b08219dbd7f52cb6e03d27c6c15fc9af9e/packages/buffetjs-styles/src/components/Button/index.js#L39)

Removing these should come with a performance improvement.

**Comment by BoyWithSilverWings** [comment]
Would love to take this up if you see this a worthy improvement.

**Comment by soupette** [comment]
@BoyWithSilverWings sure that would be very cool!

Thanks a lot
