### ISSUE TITLE
The new date picker doesn't allow change of year

### ISSUE THREAD

**Issue by abdonrd** [strapi/buffet#68]
**Describe the bug**
With the new datepicker is imposible change the year.

For example, I need to select `August 12, 1993`. I can't go month by month until 1993. 😅 

**Expected behavior**
An option like the previous date picker.

**Screenshots**

<img width="347" alt="Screenshot 2019-12-19 at 03 47 26" src="https://user-images.githubusercontent.com/1007051/71140701-4d4eff80-2212-11ea-91bc-976c7011ab65.png">

**System**
- Node.js version: `v12`
- NPM version: `v6`
- Strapi version: `v3.0.0-beta.18`
- Database: MongoDB
- Operating system: macOS

**Comment by soupette** [comment]
So the lib that we are using [react-dates](https://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default) does not have this option... However, what we can do is allowing the change of year using the input which is currently in `readonly` will that be a suitable option?

**Comment by abdonrd** [comment]
That would work for me, yes! 😄

**Comment by soupette** [comment]
I'll see what I can do then! I will try to make some modifications before January 2020

**Comment by abdonrd** [comment]
Great, thanks @soupette! 👏

**Comment by soupette** [comment]
@abdonrd  I have created a PR that allows the change of year directly from the input component.
However, I am running into an [issue](https://github.com/airbnb/react-dates/issues/1320) where I am unable to open the date picker at the selected date... Nevertheless the component is still usable.

**Comment by abdonrd** [comment]
Thanks for the update, @soupette!

**Comment by ManAnRuck** [comment]
@abdonrd 

is it possible to clear this datepicker if it's not an required field?

when I try to remove the value and click outside the old value returns and I don't see a clear button.

**Comment by soupette** [comment]
@ManAnRuck currently it is not possible and I think that it should be solved. I'll try to open up a PR to fix it. Can you open an issue so we can keep track of this bug?

**Comment by ManAnRuck** [comment]
@soupette sure, thank you :)

https://github.com/strapi/buffet/issues/97

**Comment by IamManchanda** [comment]
> I need to select August 12, 1993. I can't go month by month until 1993. 😅

A very important feature to me for my upcoming projects... 😞

Any updates on this feature dear friends?

**Comment by gbrlgmrs** [comment]
@IamManchanda I agree. My case is similar, with birthdates.

Type on the input is not working, since the datepicker appear to overwrite the value.
Even if it was possible, here in Brazil the users are very acquainted with with DD/MM/YYYY instead of MM/DD/YYYY, and maybe it cause some confusion.

My solution for now is to use text type.

**Comment by toriecr** [comment]
Is there any update on this?

**Comment by soupette** [comment]
We are planning to update the entire design system of the administration panel and we are taking in consideration all feedback provided regarding the date picker. In the meantime, we have provided a temporary fix that allows to change the date of a datepicker using the text input of the same component so a user can directly set a date.

If the provided component really does not suit your needs you can create your own datepicker component and replace the existing one in your project, you can follow this [guide](https://strapi.io/documentation/developer-docs/latest/guides/registering-a-field-in-admin.html#creating-a-new-field-in-the-administration-panel) from our official documentation, it explains how to change the WYSIWYG so you can easily apply the same logic to change the date picker.

**Comment by soupette** [comment]
The guide I provided explains how to change a field, regarding the `useStrapi` hook it allows to access the components that are added by other plugins, you don't need it in order to change the datepicker.

**Comment by crussell42** [comment]
Is there any update on this? 
Very bad user interaction with date picker.
Trying to set the date by typing in the text input is basically impossible.
Really really need a working datepicker in the admin.

**Comment by Antoine-arranz** [comment]
Hello, any news or workaround?

**Comment by MattieBelt** [comment]
Hey @Antoine-arranz,

Strapi has released a new [Design System](https://design-system.strapi.io/) for Strapi `v4`, you can checkout [the new Date component]((https://design-system-git-develop-strapijs.vercel.app/?path=/story/design-system-components-datepicker--base)).

**Comment by Antoine-arranz** [comment]
@MattieBelt Thanks !
