### ISSUE TITLE
Confusing character limit warning message

### ISSUE THREAD

**Issue by lgnov** [strapi/buffet#72]
_This issue was originally posted to [#4932](https://github.com/strapi/strapi/issues/4932#issue-546635468)_.

**Description**

In strapi admin, if the input to a text field is longer than the preset maximum length limit, it shows a warning message of `This is too high` which I feel very confusing. Similar situation to go below minimum length limit where it shows `This is too small`.

**Screenshots for the maximum/minimum length limit set to 5:**

![71949738-93e8a780-3189-11ea-8668-75b640d2c741](https://user-images.githubusercontent.com/47930782/72013073-0bfab000-3212-11ea-8e1f-dac1a7d1324a.png)
![71949742-95b26b00-3189-11ea-8e42-c73d88ae9adf](https://user-images.githubusercontent.com/47930782/72013074-0d2bdd00-3212-11ea-97eb-df5336de163a.png)

**Code snippets**

In `createYupSchema.js`, looks like both `max` and `maxLength` cases use the same error `translatedErrors.max` which is `This is too high`.

```js
case 'max':
case 'maxLength':
    schema = schema.max(validationValue, translatedErrors.max);
    break;
case 'min':
case 'minLength':
    schema = schema.min(validationValue, translatedErrors.min);
    break;
```

Would it make more sense to use `translatedErrors.maxLength`, which is `This is too long`, for the `maxLength` case? Something like this below:

```js
case 'max':
  schema = schema.max(validationValue, translatedErrors.max);
  break;
case 'maxLength':
  schema = schema.max(validationValue, translatedErrors.maxLength);
  break;
case 'min':
  schema = schema.min(validationValue, translatedErrors.min);
  break;
case 'minLength':
  schema = schema.min(validationValue, translatedErrors.minLength);
  break;
```

**Comment by soupette** [comment]
I completely agree!
