### ISSUE TITLE
"Date" type picker doesn't let you pick year/decade

### ISSUE THREAD

**Issue by tannuxie** [strapi/buffet#77]
**Describe the bug**
With the old datetime data type, the date picker let you "zoom out" from the "month/day" picker to pick year or even decade, which is very useful for the project I'm working on. Having to click dozens or hundreds of times to scroll back to a certain date is a pretty major inconvenience.

**Steps to reproduce the behavior**
Using latest version of strapi, add a date type field.

**Expected behavior**
I expected the date data type to have the same type of date picker as the old datetime data type picker.

**System**
- Node.js version: 10.18
- NPM version: 6.13.4
- Yarn version: 1.21.1
- Strapi version: 18.3
- Database: Postgres
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Perfect, I transferred this issue to Buffet repo and re-open the issue.

**Comment by soupette** [comment]
@lauriejim this issue has been fixed, the input component in the datepicker allows you to change the date directly.
