### ISSUE TITLE
[FR] date picker clearing

### ISSUE THREAD

**Issue by ManAnRuck** [strapi/buffet#97]
I think it's necessary to clear an optional date picker value.

Currently it's not possible to remove a value from a optional date picker field.

A clearing option for optional date picker would be glad  :) 
For required dates it's fine without.

**Comment by weidox** [comment]
This one is annoying because we're using some dates to control when certain things are triggered at (like an object gets archived), and once set it's not possible to cleanly revert via admin UI.
